---
# tasks file for ansible-role-hp-diag

 - name: install hpssacli
   package:
        name: "hpssacli"
        state: "present"

 - name: pip install python-hostlist
   pip:
        name: "python-hostlist"
        state: "present"
   when: hpssacli_diag_install_with_pip

 - name: create directory hpssacli_diag_store_path
   file: 
        path: "{{ hpssacli_diag_store_path }}"
        state: "directory"
        mode: "0750"
        owner: "{{ hpssacli_diag_store_owner }}"

 - name: add a cronjob to run hpssacli
   cron:
        name: "ansible-pull"
        user: "{{ hpssacli_diag_store_owner }}"
        job: "/bin/nice /usr/bin/sudo {{ hpssacli_diag_sbin_path }} ctrl all diag file={{ hpssacli_diag_store_path }}/hpssacli_diag_$(hostname -s)_$(date +\\%Y\\%m\\%d_\\%s).zip >/dev/null 2>&1"
        minute: "{{ hpssacli_diag_cron_minute_interval | default('0')}}"
        hour: "{{ hpssacli_diag_cron_hour_interval | default('02') }}"
        day: "{{ hpssacli_diag_cron_day_interval | default('*') }}"
        month: "{{ hpssacli_diag_cron_month_interval | default('*') }}"
        weekday: "{{ hpssacli_diag_cron_weekday_interval | default('1') }}"
        cron_file: hpssacli_diag
        state: "{{ hpssacli_diag_cron_state | default('present') }}"
